---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.10.0 incluye varias funciones y mejoras nuevas. 
---
= Novedades de Cloud Volumes ONTAP 9.10.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.10.0 incluye varias funciones y mejoras nuevas.

Las últimas versiones de BlueXP también incluyen funciones y mejoras adicionales. Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de la versión de BlueXP"^] para obtener más detalles.



== Ya no se admiten las instancias c4, m4 y r4 (28 de octubre de 2022)

En AWS, los tipos de instancias c4, m4 y r4 EC2 ya no son compatibles con Cloud Volumes ONTAP. Si tiene un sistema existente que se ejecuta en un tipo de instancia c4, m4 o r4, debe cambiar a un tipo de instancia en la familia de instancias c5, m5 o r5.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprenda a cambiar el tipo de instancia de EC2 para Cloud Volumes ONTAP"^].

Consulte link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Soporte de NetApp"^] para obtener más información acerca del fin de la disponibilidad y la compatibilidad con estos tipos de instancia.



== 9.10.0 GA (4 de octubre de 2021)

La versión de GA de 9.10.0 está disponible en AWS, Azure y Google Cloud. Esta versión incluye las siguientes funciones y mejoras nuevas.



=== Rendimiento de escritura mejorado

Hemos mejorado el rendimiento de escritura de Cloud Volumes ONTAP cuando se activa la alta velocidad de escritura.



=== Ha aumentado el tamaño del disco NVRAM en Azure

El tamaño del disco de NVRAM se aumentó de 128 GIB a 512 GIB para los nuevos sistemas Cloud Volumes ONTAP en Azure.


NOTE: Si elige un sistema de nodo único y la máquina virtual admite Ultra SSD, entonces el sistema utiliza un Ultra SSD de 32 GIB para NVRAM, en lugar de un SSD Premium de 512 GIB.



== Versión necesaria del conector BlueXP

El conector BlueXP debe estar ejecutando la versión 3.9.11 o posterior para implementar nuevos sistemas Cloud Volumes ONTAP 9.10.0 y actualizar los sistemas existentes a la versión 9.10.0.



== Notas de actualización

* Las actualizaciones de Cloud Volumes ONTAP deben completarse desde BlueXP. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.
* Puede actualizar a Cloud Volumes ONTAP 9.10.0 desde la versión 9.9.1. BlueXP le solicitará que actualice sus sistemas Cloud Volumes ONTAP 9.9.1 existentes a la versión 9.10.0.
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Obtenga información sobre cómo actualizar cuando BlueXP lo notifique"^].

* La actualización de un único sistema de nodos desconecta el sistema hasta 25 minutos, durante los cuales se interrumpe la I/O.
* Actualizar un par de alta disponibilidad no provoca interrupciones y la I/o se realiza de forma ininterrumpida. Durante este proceso de actualización no disruptiva, cada nodo se actualiza conjuntamente para seguir proporcionando I/o a los clientes.




=== DS3_v2

A partir de la versión 9.9.1, el tipo de máquina virtual DS3_v2 ya no es compatible con sistemas Cloud Volumes ONTAP nuevos y existentes. Si ya tiene un sistema en ejecución en este tipo de equipo virtual, deberá cambiar los tipos de equipos virtuales antes de actualizar a 9.10.0.
